sudo: required

language: go

services:
  - docker

go:
  - 1.8.3

os:
  - linux

before_install:
  - make setup-minikube-ci
  - go get github.com/mattn/goveralls
  - ./minikube start --vm-driver=none --use-vendored-driver --kubernetes-version=v1.7.0-alpha.2

install:
  - make setup-ci

script:
  - make build-all-race
  - make test-race
  - make minikube-test
  - make coveralls
